### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/strafes-net-clients#6]
No collaborator has yet to confirm to contribute to this language.

- [x] User confirms will fix.
- [x] Reviewed & made changes.
- [ ] Approved for finalization.

**Comment by insyri** [comment]
@dowoge Accepted via dms.

**Comment by dowoge** [comment]
I'm doing stuff. (i think)

**Comment by insyri** [comment]
Future note: `describe` was never referenced in the code, so it being undefined or type of any is something out of our knowledge for as far as we know.
